[package]
name = "entry"
version = "0.1.0"
edition = "2021"

[dependencies]
dips = { path = "../dips" }
native-dialog = "0.7.0"
pretty_env_logger = "0.5.0"
slint = "1.10.0"

[build-dependencies]
slint-build = "1.10.0"
