import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";


export component MainWindow inherits Window {
    width: 640px;
    height: 480px;

    callback find_input_path() -> string;
    callback get_thumbnail(string) -> image;
    callback run_dips(string);

    VerticalBox {
        thumbnail := Image {}
        path := Text {
            text: "Choose an input file";
        }
        HorizontalBox {
            Button {
                text: "Input";
                clicked => {
                    path.text = root.find_input_path();
                    thumbnail.source = root.get_thumbnail(path.text);
                }
            }
            Button {
                text: "Run";
                clicked => {
                    root.run_dips(path.text);
                }
            }
        }
    }

    
    // VerticalBox {
    //     label := Text {
    //         text: "Input Not Specified";
    //     }
    //     Button {
    //         text: "Input";
    //         clicked => {
    //             label.text = root.find_input_path();
    //         }
    //     }
    //     Button {
    //         text: "Run";
    //         clicked => {
    //             root.run_dips(label.text);
    //         }
    //     }
    // }
}
