[package]
name = "entry"
version = "0.1.0"
edition = "2024"

[dependencies]
dips = { path = "../dips" }
directories = "6.0.0"
image = "0.25.5"
log = "0.4.26"
native-dialog = "0.7.0"
pretty_env_logger = "0.5.0"
slint = "1.10.0"
smol = "2.0.2"

[build-dependencies]
slint-build = "1.10.0"
