[package]
name = "dips"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
gstreamer = "0.23.5"
gstreamer-app = "0.23.5"
gstreamer-pbutils = "0.23.5"
gstreamer-video = "0.23.5"
image = "0.25.5"
log = "0.4.25"
pollster = "0.4.0"
wgpu = "24.0.1"
